#
# (C) Copyright 2019 Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier:     GPL-2.0+
#

ifneq ($(CONFIG_TPL_BUILD)$(CONFIG_TPL_TINY_FRAMEWORK),yy)
obj-y += syscon_rv1126.o
endif
obj-y += clk_rv1126.o
obj-y += rv1126.o
