#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 2017 by YH_HSIEH <yh_hsieh@realtek.com>
# 

obj-y	:= board.o
