#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 2015 by Tom Ting <tom_ting@realtek.com>
#

obj-y  += clock.o
obj-y  += timer.o
obj-y  += reset.o
obj-y  += dram.o
obj-y  += hwinit.o
obj-y  += cpu.o
obj-y  += factorylib.o
obj-y  += mcp.o
obj-y  += md.o
obj-y  += mem.o
obj-y  += bootparam.o 	
obj-y  += ddr.o
obj-y  += ir.o
obj-y  += usb.o
obj-y  += usb-phy.o


obj-$(CONFIG_CMD_GICTEST) += gic.o
