#!/bin/sh /etc/rc.common

START=39

USE_PROCD=1

auto_mount() {
	[ "`uci -q get fstab.@global[0].anon_mount`" = "1" ] && /usr/libexec/blockmount.sh
	return 0
}

boot() {
	auto_mount
    start "$@"
}

service_triggers() {
	procd_add_reload_trigger "fstab"
}

reload_service() {
	auto_mount
}

start_service() {
	return 0
}
