#!/bin/sh /etc/rc.common

START=97

check_kernel() {
	local major=$1
	local minor=$2
	[ "$major" -gt 5 -o \( "$major" -eq 5 -a "$minor" -ge 4 \) ]
}

boot() {
	if check_kernel `uname -r | grep -Eo '[0-9]+\.[0-9]+' | sed 's/\./ /g'`; then
		rm -f /overlay/upper/usr/lib/samba/vfs/io_uring.so /ext_overlay/upper/usr/lib/samba/vfs/io_uring.so
	elif [ -f /usr/lib/samba/vfs/io_uring.so ]; then
		rm -f /usr/lib/samba/vfs/io_uring.so
	fi
}
