#!/bin/sh /etc/rc.common

START=34
STOP=86

BACKUP_FILE="/etc/odhcpd-piodir-backup.tar.gz"

boot() {
	[ -s "$BACKUP_FILE" ] || return 0
	tar -xzf "$BACKUP_FILE" -C /
	rm -f "$BACKUP_FILE"
}

shutdown() {
	local piodir=$(uci -q get dhcp.odhcpd.piodir)
	[ -n "$piodir" ] || return 0
	# only backup if piodir is in /tmp/
	[ -z "${piodir##/tmp/*}" ] || return 0
	[ -d "$piodir" ] || return 0

	tar -czf "$BACKUP_FILE" -C / "$piodir" || rm -f "$BACKUP_FILE"
}
