#
# Copyright (c) 2019 Fuzhou Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-$(CONFIG_CHARGER_BQ25700) += bq25700_charger.o
obj-$(CONFIG_CHARGER_BQ25890) += bq25890_charger.o
