
obj-$(CONFIG_FASTBOOT_RTK) += fastboot_cmd.o
obj-$(CONFIG_FASTBOOT_RTK) += sparse_img.o
obj-$(CONFIG_FASTBOOT_RTK) += tar_img.o
obj-$(CONFIG_FASTBOOT_RTK) += layout.o
obj-$(CONFIG_FASTBOOT_RTK) += part.o
obj-$(CONFIG_FASTBOOT_RTK) += mbr.o
obj-$(CONFIG_FASTBOOT_RTK) += gpt.o
obj-$(CONFIG_FASTBOOT_RTK) += fw.o
