#!/bin/sh /etc/rc.common

START=09

boot() {
	local kmod
	local enable="$( uci -q get kmods.kmods.enable )"
	echo "$enable" | grep -qFw "xe-sriov" && return 0
	if echo "$enable" | grep -qFw "i915-sriov" || is_white_list; then
		local FAILFILE=/etc/config/.i915_sriov_boot
		local count=$(cat $FAILFILE)
		[[ -n "$count" ]] || count=0
		[[ $count -le 2 ]] || return 0
		count=$(( $count + 1 ))
		echo "$count" > $FAILFILE
		sync $FAILFILE
		[[ $count -le 2 ]] || return 0

		local release="$(uname -r)"
		[[ -n "$release" ]] || return 0

		echo "enable i915-sriov" >>/dev/kmsg
		ls /lib/modules/$release/i915-sriov/ 2>/dev/null | while read kmod; do
			if [[ "$kmod" = "*.ko" ]]; then
				[[ -f /lib/modules/$release/$kmod ]] || continue
				mount --bind -r /lib/modules/$release/i915-sriov/$kmod /lib/modules/$release/$kmod
			else
				if [[ -f /etc/modules.d/$kmod ]]; then
					mount --bind -r /lib/modules/$release/i915-sriov/$kmod /etc/modules.d/$kmod
				else
					local target=$(ls /etc/modules.d/ 2>/dev/null | grep "^[0-9_-]*-$kmod\$" | head -1)
					[[ -n "$target" ]] || continue
					mount --bind -r /lib/modules/$release/i915-sriov/$kmod /etc/modules.d/$target
				fi
			fi
		done
	fi
}

is_white_list() {
	grep -qFw 0x8086 /sys/devices/pci0000:00/0000:00:02.0/vendor || return 1
	[[ "$(($(cat /sys/devices/pci0000:00/0000:00:02.0/class) & 0xff0000 ^ 0x030000))" = "0" ]] || return 1
	white_list | grep -v '^#' | tr '[A-Z]' '[a-z]' | sed 's/^\</0x/' | \
		grep -qFf /sys/devices/pci0000:00/0000:00:02.0/device || return 1
	echo "$(cat /sys/devices/pci0000:00/0000:00:02.0/device) is in i915-sriov white list" >>/dev/kmsg
	return 0
}

white_list() {
	echo '
# ADL-S
4680
4682
4688
468A
468B
4690
4692
4693
# ADL-P
46A0
46A1
46A2
46A3
46A6
46A8
46AA
462A
4626
4628
46B0
46B1
46B2
46B3
46C0
46C1
46C2
46C3
# ADL-N
46D0
46D1
46D2
46D3
46D4
# RPL-S
A780
A781
A782
A783
A788
A789
A78A
A78B
# RPL-U
A721
A7A1
A7A9
A7AC
A7AD
# RPL-P
A720
A7A0
A7A8
A7AA
A7AB
# DG2
56A0
56A1
56A2
56BE
56BF
5690
5691
5692
56A5
56A6
56B0
56B1
56BA
56BB
56BC
56BD
5693
5694
5695
56A3
56A4
56B2
56B3
5696
5697
# ARL
7D51
7DD1
7D41
7D67
B640
# MTL
7D40
7D45
7D55
7D60
7DD5
# PVC
0B69
0B6E
0BD4
0BD5
0BD6
0BD7
0BD8
0BD9
0BDA
0BDB
0BE0
0BE1
0BE5
# LNL
6420
64A0
64B0
# BMG
E202
E209
E20B
E20C
E20D
E210
E211
E212
E216
E220
E221
E222
E223
# PTL
B080
B081
B082
B083
B084
B085
B086
B087
B08F
B090
B0A0
B0B0
# WCL
FD80
FD81
# NVL-S
D740
D741
D742
D743
D744
D745
# CRI
674C
'
}
