#
# (C) Copyright 2019 Rockchip Electronics Co., Ltd.
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y += test-rockchip.o
obj-y += test-boot.o
obj-y += test-download.o
ifdef CONFIG_RKIMG_BOOTLOADER
obj-y += test-display.o
obj-y += test-misc.o
endif
obj-y += test-net.o
obj-y += test-power.o
obj-y += test-storage.o
